# Generated by Django 5.0.4 on 2025-04-18 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อโรงเรียน')),
                ('abbreviation', models.CharField(blank=True, max_length=30, verbose_name='ตัวย่อชื่อโรงเรียน')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
            ],
            options={
                'verbose_name': 'โรงเรียน',
                'verbose_name_plural': 'โรงเรียน',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 'ชั้นปีที่ 1'), (2, 'ชั้นปีที่ 2'), (3, 'ชั้นปีที่ 3'), (4, 'ชั้นปีที่ 4'), (5, 'ชั้นปีที่ 5'), (6, 'ชั้นปีที่ 6')], verbose_name='ชั้นปี')),
                ('room_number', models.CharField(max_length=20, verbose_name='ทับ')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='apis.school')),
            ],
            options={
                'verbose_name': 'ห้องเรียน',
                'verbose_name_plural': 'ห้องเรียน',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('gender', models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง'), ('อื่นๆ', 'อื่นๆ')], max_length=10, verbose_name='เพศ')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='apis.classroom')),
            ],
            options={
                'verbose_name': 'นักเรียน',
                'verbose_name_plural': 'นักเรียน',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('gender', models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง'), ('อื่นๆ', 'อื่นๆ')], max_length=10, verbose_name='เพศ')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='apis.school')),
            ],
            options={
                'verbose_name': 'คุณครู',
                'verbose_name_plural': 'คุณครู',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='teachers',
            field=models.ManyToManyField(related_name='classrooms', to='apis.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('grade', 'room_number', 'school')},
        ),
    ]
